/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export type DeliveryHistoryChangeType =
  (typeof DeliveryHistoryChangeType)[keyof typeof DeliveryHistoryChangeType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeliveryHistoryChangeType = {
  NUMBER_0: 0,
  NUMBER_1: 1
} as const
