/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export interface DeliveryEntryDto {
  /** @nullable */
  finishedProccessing?: string | null
  id?: number
  /** @nullable */
  startedProccessing?: string | null
  zoneId?: number
}
