/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */
import type { LogType } from './logType'
import type { DeliveryHistoryEntityPropertyChange } from './deliveryHistoryEntityPropertyChange'
import type { DeliveryHistoryChangeType } from './deliveryHistoryChangeType'

export interface DeliveryChangeDto {
  /** @nullable */
  changeDate?: string | null
  entityId?: number
  /** @nullable */
  from?: string | null
  logType?: LogType
  propertyName?: DeliveryHistoryEntityPropertyChange
  /** @nullable */
  to?: string | null
  type?: DeliveryHistoryChangeType
}
