/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export interface DeliveryFormDto {
  /**
   * @minLength 1
   * @maxLength 100
   */
  cmr: string
  deliveryTime?: string
  isApproved?: boolean
  /** @nullable */
  markers?: number[] | null
  packages?: number
  pallets?: number
  pieces?: number
  /**
   * @minLength 1
   * @maxLength 100
   */
  receptionNumber: string
  /**
   * @minLength 1
   * @maxLength 100
   */
  systemNumber: string
  /**
   * @minLength 1
   * @maxLength 100
   */
  truckNumber: string
  vendorId?: number
}
