/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export interface DeliveryEntryDetailsDto {
  /** @nullable */
  finishedProccessing?: string | null
  id?: number
  packages?: number
  pallets?: number
  pieces?: number
  /** @nullable */
  startedProccessing?: string | null
  /** @nullable */
  zoneName?: string | null
}
