/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */
import type { DeliveryDto } from './deliveryDto'

export interface DeliveryDtoPageDto {
  count?: number
  hasNext?: boolean
  hasPrevious?: boolean
  /** @nullable */
  results?: DeliveryDto[] | null
}
