/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */
import type { EntriesProcessingDetails } from './entriesProcessingDetails'
import type { DeliveryMarkerDto } from './deliveryMarkerDto'

export interface DeliveryDto {
  /** @nullable */
  approvedOn?: string | null
  /** @nullable */
  createdAt?: string | null
  /** @nullable */
  deliveryTime?: string | null
  entriesFinishedProcessing?: number
  entriesFinishedProcessingDetails?: EntriesProcessingDetails
  entriesWaitingProcessing?: number
  entriesWaitingProcessingDetails?: EntriesProcessingDetails
  id?: number
  /** @nullable */
  markers?: DeliveryMarkerDto[] | null
  /** @nullable */
  receptionNumber?: string | null
  /** @nullable */
  status?: string | null
  /** @nullable */
  systemNumber?: string | null
  /** @nullable */
  vendorName?: string | null
}
