/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */
import type { Change } from './change'

export interface DeliveryHistoryDto {
  /** @nullable */
  changes?: Change[] | null
  id?: number
}
