/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */
import type { DeliveryEntryDto } from './deliveryEntryDto'
import type { DeliveryMarkerDto } from './deliveryMarkerDto'

export interface DeliveryDto {
  /** @nullable */
  cmr?: string | null
  deliveryTime?: string
  /** @nullable */
  entries?: DeliveryEntryDto[] | null
  id?: number
  isApproved?: boolean
  /** @nullable */
  markers?: DeliveryMarkerDto[] | null
  packages?: number
  pallets?: number
  pieces?: number
  /** @nullable */
  receptionNumber?: string | null
  /** @nullable */
  status?: string | null
  /** @nullable */
  systemNumber?: string | null
  /** @nullable */
  truckNumber?: string | null
  vendorId?: number
  /** @nullable */
  vendorName?: string | null
}
