/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */
import type { DifferenceStatus } from './differenceStatus'

export interface DifferenceDto {
  /** @nullable */
  activeNumber?: string | null
  /** @nullable */
  adminComment?: string | null
  /** @nullable */
  comment?: string | null
  count?: number
  /** @nullable */
  createdAt?: string | null
  /** @nullable */
  deliverySystemNumber?: string | null
  id?: number
  /** @nullable */
  internalNumber?: string | null
  /** @nullable */
  receptionNumber?: string | null
  status?: DifferenceStatus
  /** @nullable */
  type?: string | null
  /** @nullable */
  zone?: string | null
}
