/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export interface DifferenceFormDto {
  /**
   * @minLength 1
   * @maxLength 350
   */
  activeNumber: string
  /**
   * @minLength 0
   * @maxLength 2000
   * @nullable
   */
  comment?: string | null
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  count: number
  deliveryId: number
  differenceTypeId: number
  /**
   * @minLength 1
   * @maxLength 350
   */
  internalNumber: string
  /**
   * @minLength 1
   * @maxLength 350
   */
  receptionNumber: string
  zoneId: number
}
