/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export interface DifferenceAdminCommentDto {
  /**
   * @minLength 0
   * @maxLength 2000
   * @nullable
   */
  adminComment?: string | null
}
