/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export interface DifferenceTypeFormDto {
  /**
   * @minLength 1
   * @maxLength 250
   * @nullable
   */
  name?: string | null
}
