/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export type EntryStatuses = (typeof EntryStatuses)[keyof typeof EntryStatuses]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntryStatuses = {
  Waiting: 'Waiting',
  Processing: 'Processing',
  Finished: 'Finished'
} as const
