/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export type EntryStatuses = (typeof EntryStatuses)[keyof typeof EntryStatuses]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntryStatuses = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2
} as const
