/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */
import type { ZoneDto } from './zoneDto'

export interface EntryDto {
  deliveryId?: number
  /** @nullable */
  finishedProccessing?: string | null
  id?: number
  packages?: number
  pallets?: number
  pieces?: number
  /** @nullable */
  startedProccessing?: string | null
  zone?: ZoneDto
}
