/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */
import type { EntryDeliveryDetailsDto } from './entryDeliveryDetailsDto'
import type { EntryZoneDto } from './entryZoneDto'

export interface EntryDto {
  /** @nullable */
  createdAt?: string | null
  deliveryDetails?: EntryDeliveryDetailsDto
  /** @nullable */
  finishedProccessing?: string | null
  id?: number
  packages?: number
  pallets?: number
  pieces?: number
  /** @nullable */
  startedProccessing?: string | null
  zone?: EntryZoneDto
}
