/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export interface EntryFormDto {
  deliveryId: number
  /**
   * @minimum 0
   * @maximum 5000
   */
  packages?: number
  /**
   * @minimum 0
   * @maximum 5000
   */
  pallets?: number
  /**
   * @minimum 0
   * @maximum 5000
   */
  pieces?: number
  zoneId: number
}
