/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export interface EntryDeliveryDetailsDto {
  id?: number
  /** @nullable */
  receptionNumber?: string | null
  /** @nullable */
  systemNumber?: string | null
  /** @nullable */
  vendorName?: string | null
}
