/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Swagger Petstore
 * A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification
 * OpenAPI spec version: 1.0.0
 */

export interface ErrorModel {
  code: number
  message: string
}
