/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */
import type { EntryStatuses } from './entryStatuses'

export type GetApiZoneEntriesParams = {
  zoneId?: number
  statuses?: EntryStatuses[]
}
