/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export type GetApiDifferenceAllWithDeletedParams = {
  PageNumber?: number
  PageSize?: number
  SearchQuery?: string
}
