/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /**
   * @minLength 5
   * @maxLength 250
   * @nullable
   */
  password?: string | null
  /**
   * @minLength 1
   * @maxLength 100
   * @nullable
   */
  username?: string | null
}
