/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export type LogType = (typeof LogType)[keyof typeof LogType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3
} as const
