/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */
import type { MarkerDeliveryDto } from './markerDeliveryDto'
import type { MarkerVendorDto } from './markerVendorDto'
import type { MarkerZoneDto } from './markerZoneDto'

export interface MarkerDto {
  /** @nullable */
  deliveries?: MarkerDeliveryDto[] | null
  id?: number
  /** @nullable */
  name?: string | null
  /** @nullable */
  vendors?: MarkerVendorDto[] | null
  /** @nullable */
  zones?: MarkerZoneDto[] | null
}
