/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 * OpenAPI spec version: 1.0.7
 */
import type { OrderStatus } from './orderStatus'

export interface Order {
  complete?: boolean
  id?: number
  petId?: number
  quantity?: number
  shipDate?: string
  /** Order Status */
  status?: OrderStatus
}
