/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export interface ProblemDetails {
  /** @nullable */
  detail?: string | null
  /** @nullable */
  instance?: string | null
  /** @nullable */
  status?: number | null
  /** @nullable */
  title?: string | null
  /** @nullable */
  type?: string | null
  [key: string]: unknown
}
