/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  /**
   * @minLength 1
   * @maxLength 150
   * @nullable
   */
  email?: string | null
  /**
   * @minLength 5
   * @maxLength 250
   * @nullable
   */
  password?: string | null
  /** @nullable */
  roleId?: string | null
  /**
   * @minLength 1
   * @maxLength 100
   * @nullable
   */
  username?: string | null
}
