/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export interface UserDto {
  /** @nullable */
  email?: string | null
  /** @nullable */
  id?: string | null
  /** @nullable */
  role?: string | null
  /** @nullable */
  roles?: string[] | null
  /** @nullable */
  routePermissionNames?: string[] | null
  /** @nullable */
  userName?: string | null
}
