/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export interface VendorFormDto {
  /** @nullable */
  markerIds?: number[] | null
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string
  /**
   * @minLength 1
   * @maxLength 100
   */
  systemNumber: string
}
