/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export interface ZoneEntryDto {
  deliveryId?: number
  /** @nullable */
  finishedProccessing?: string | null
  packages?: number
  pallets?: number
  pieces?: number
  /** @nullable */
  startedProccessing?: string | null
}
