/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export interface ZoneFormDto {
  /** @nullable */
  isFinal?: boolean | null
  /** @nullable */
  markerIds?: number[] | null
  /**
   * @minLength 1
   * @maxLength 500
   */
  name: string
}
