/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export interface ZoneVendorDto {
  vendorId?: number
  /** @nullable */
  vendorName?: string | null
  /** @nullable */
  vendorSystemNumber?: string | null
}
