/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */
import type { ZoneMarkerDto } from './zoneMarkerDto'

export interface ZoneDetailsDto {
  /** @nullable */
  createdAt?: string | null
  id?: number
  isFinal?: boolean
  /** @nullable */
  markers?: ZoneMarkerDto[] | null
  /** @nullable */
  name?: string | null
}
